--3. 부서번호(DNO)가 10 또는 30 에 속하고, 
--부서번호별, 부서명별 최고급여가 3000 이상인 사원의 
--부서번호, 부서명, 최고급여를 화면에 표시하세요


SELECT D.DNAME,D.DNO, E.SALARY FROM EMPLOYEE E,
DEPARTMENT D
WHERE D.DNO =E.DNO
AND D.DNO IN  (10,30);


SELECT D.DNAME, D.DNO, MAX(E.SALARY) AS 최고급여
FROM EMPLOYEE E
JOIN DEPARTMENT D ON D.DNO = E.DNO
WHERE E.SALARY > 3000
GROUP BY D.DNO, D.DNAME;



SELECT D.DNAME, D.DNO, MAX(E.SALARY) AS 최고급여
FROM EMPLOYEE E
JOIN DEPARTMENT D ON D.DNO = E.DNO
WHERE E.SALARY > 3000
AND D.DNO IN (10, 30)
GROUP BY D.DNO, D.DNAME;


